include(FetchContent)
set(FETCHCONTENT_QUIET ON)
FetchContent_Declare(nlohmann_json GIT_REPOSITORY https://github.com/nlohmann/json GIT_TAG v3.12.0 GIT_SHALLOW TRUE SYSTEM)
FetchContent_Declare(miniz GIT_REPOSITORY https://github.com/richgel999/miniz GIT_TAG 3.1.0 GIT_SHALLOW TRUE SYSTEM)
FetchContent_Declare(googletest GIT_REPOSITORY https://github.com/google/googletest GIT_TAG v1.17.0 GIT_SHALLOW TRUE SYSTEM)
FetchContent_Declare(cdt GIT_REPOSITORY https://github.com/artem-ogre/CDT GIT_TAG 1.4.5 GIT_SHALLOW TRUE SOURCE_SUBDIR CDT SYSTEM)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_FUZZERS OFF CACHE BOOL "" FORCE)
set(INSTALL_GTEST OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(nlohmann_json miniz googletest cdt)
find_package(Eigen3 REQUIRED NO_MODULE)
if(Eigen3_VERSION VERSION_LESS 3.4)
  message(FATAL_ERROR "Eigen >= 3.4 required")
endif()
include(GoogleTest)
